version: '3'
services:
  postgres:
    container_name: 'postgres'
    image: postgres:latest
    ports:
      - 6500:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Ranking
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - sudoku_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5555:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: Example123
  #   links:
  #     - postgres
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   restart: unless-stopped
  # app:
  #   image: next-prisma-docker
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
volumes:
  sudoku_postgres_data:
  pgadmin-data: